### ISSUE TITLE
Prebuilt APKs?

### ISSUE THREAD

**Issue by Mennaruuk** [Henry-Hiles/QWeather#1]
I tried accessing the debug builds through [nightly.link](https://nightly.link/Henry-Hiles/QWeather/workflows/build/main/QWeather.zip), but it keeps telling me _Error 404 - Not found_

**Comment by Henry-Hiles** [comment]
Oh, looks like the artifact expired, one moment please!

**Comment by Henry-Hiles** [comment]
I need to wait for the action to finish then I'll give you a new link. (Please do aware that this project is pre-release and will be buggy, PRs appreciated)

**Comment by Henry-Hiles** [comment]
Okay so I ran the action, but the link still doesn't work, lets give it ~20 mins and see if it fixes itself, If not I'll link you a direct nightly for now

**Comment by Henry-Hiles** [comment]
The link in the readme should now be fixed.
